# Generated by Django 5.1.1 on 2025-03-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenselimit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
    ]
