# Generated by Django 5.1.1 on 2025-04-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
